package net.hycrafthd.worldgenerationprofiler;

import net.minecraftforge.fml.common.ModMetadata;

public class Metadata extends ModMetadata {
	
	public Metadata() {
		this.modId = "worldgenerationprofiler";
		this.name = "World Generation Profiler";
		this.version = "@VERSION@";
		this.description = "https://www.curseforge.com/minecraft/mc-mods/worldgeneration-profiler";
		this.autogenerated = false;
	}
	
}
